### ISSUE TITLE
Impossible to start node

### ISSUE THREAD

**Issue by pskmsc** [henrikingo/impressionist#11]
Hello,

I got an issue to start the impressionist, I got an error message about electron.
I tried with root account to be sure, I had the same result; 

npm start

> impressionist@0.1.0 start /root/impressionist
> electron .

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! impressionist@0.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the impressionist@0.1.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the impressionist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs impressionist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls impressionist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/impressionist/npm-debug.log

The log file : 

 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle impressionist@0.1.0~prestart: impressionist@0.1.0
6 silly lifecycle impressionist@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle impressionist@0.1.0~start: impressionist@0.1.0
8 verbose lifecycle impressionist@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle impressionist@0.1.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/impressionist/node_modules/.bin:/bin:/sbin:/usr/bin:/usr/sbin::/usr/local/bin
10 verbose lifecycle impressionist@0.1.0~start: CWD: /root/impressionist
11 silly lifecycle impressionist@0.1.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle impressionist@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle impressionist@0.1.0~start: Failed to exec start script
14 verbose stack Error: impressionist@0.1.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid impressionist@0.1.0
16 verbose cwd /root/impressionist
17 error Linux 4.4.0-59-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error impressionist@0.1.0 start: `electron .`
22 error Exit status 1
23 error Failed at the impressionist@0.1.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the impressionist package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs impressionist
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls impressionist
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by pskmsc** [comment]
Hello,

I solved my issue by myself.

Regards
