### ISSUE TITLE
Fails to install, probably due to NPM package vulnerabilities

### ISSUE THREAD

**Issue by cems2** [henrikingo/impressionist#33]
when running npm install I get reports of critical vulnerabilities in packages requires.  Ignoring this and trying to start this code anyhow I get the following error message
npm start

> impressionist@0.1.0 start /home/cems2/impressionist/impressionist
> electron .

/home/cems2/impressionist/impressionist/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! impressionist@0.1.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the impressionist@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cems2/.npm/_logs/2021-01-02T21_02_44_616Z-debug.log

I note that the log file listed above is doesn't seem to exist either.

**Comment by cems2** [comment]
more output:
```npm audit fix
updated 1 package in 0.686s

4 packages are looking for funding
  run `npm fund` for details

fixed 1 of 7 vulnerabilities in 157 scanned packages
  3 vulnerabilities required manual review and could not be updated
  1 package update for 3 vulnerabilities involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
(base) cems@pn2001094:~/Documents/JamieMorton/impressionist$ npm audit fix --force
npm WARN using --force I sure hope you know what you are doing.

> core-js@3.8.2 postinstall /home/cems/Documents/JamieMorton/impressionist/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@11.1.1 postinstall /home/cems/Documents/JamieMorton/impressionist/node_modules/electron
> node install.js



^C
(base) cems@pn2001094:~/Documents/JamieMorton/impressionist$ npm start

> impressionist@0.1.0 start /home/cems/Documents/JamieMorton/impressionist
> electron .

/home/cems/Documents/JamieMorton/impressionist/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/cems/Documents/JamieMorton/impressionist/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/cems/Documents/JamieMorton/impressionist/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/cems/Documents/JamieMorton/impressionist/node_modules/electron/cli.js:3:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! impressionist@0.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the impressionist@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by grempa** [comment]
same here +1

**Comment by nord64** [comment]
Did anybody solve the issue?
